apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: airport
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: airport
    spec:
      containers:
      - name: airport
        image: gcr.io/responsive-sun-223918/airport 
        ports:
        - name: airport-port
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: airport-port
          initialDelaySeconds: 160
          timeoutSeconds: 60

